// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos-layout/internal/service"
	"github.com/go-kratos/kratos-layout/internal/thirdmodule"
	"github.com/go-kratos/kratos-layout/internal/thirdservice"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, thirdModule *conf.ThirdModule, thirdService *conf.ThirdService, logger log.Logger) (*kratos.App, func(), error) {
	module, cleanup, err := thirdmodule.NewModule(thirdModule, logger)
	if err != nil {
		return nil, nil, err
	}
	thirdserviceThirdService := thirdservice.NewService(thirdService, logger)
	serviceService := service.NewService(module, logger, thirdserviceThirdService)
	grpcServer := server.NewGRPCServer(confServer, module, serviceService, logger)
	httpServer := server.NewHTTPServer(confServer, module, serviceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
