// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FoosColumns holds the columns for the "foos" table.
	FoosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
	}
	// FoosTable holds the schema information for the "foos" table.
	FoosTable = &schema.Table{
		Name:       "foos",
		Columns:    FoosColumns,
		PrimaryKey: []*schema.Column{FoosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FoosTable,
	}
)

func init() {
}
